services:
  db:
    image: postgres:16.10
    restart: always 
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: db-ecommerce-gluten-free
    volumes:
      - ./postgres:/var/lib/postgresql